name: Build AtomEngine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_EXAMPLES=OFF

    - name: Build AtomEngine Library
      run: cmake --build build --target AtomEngine

    - name: Verify Build Output
      run: |
        if [ ! -f build/libAtomEngine.a ]; then
          echo "Build failed: libAtomEngine.a not found"
          exit 1
        fi